window.QUIZ_DATA = {
  id: "統計学1_期末",
  title: "統計学1 期末 Rコード一般形",
  questions: [
    // ===== 第1章: 基本操作 =====
    { id: "s01-t01", chapter: "第1章 基本操作", type: "term",
      front: "Rで計算結果をオブジェクトに保存するときに使う演算子の書き方は？",
      back: "<code>オブジェクト名 &lt;- 値</code>（代入演算子 <code>&lt;-</code> を使う）" },
    { id: "s01-t02", chapter: "第1章 基本操作", type: "term",
      front: "Rでコメントを書くための記号は？",
      back: "<code>#</code>（シャープ記号以降がコメントになり、実行されない）" },
    { id: "s01-t03", chapter: "第1章 基本操作", type: "term",
      front: "Rで平方根を計算する関数は？",
      back: "<code>sqrt(数値)</code>" },
    { id: "s01-t04", chapter: "第1章 基本操作", type: "term",
      front: "Rでべき乗を計算する演算子は？",
      back: "<code>^</code>（例: <code>5 ^ 3</code> → 125）" },
    { id: "s01-t05", chapter: "第1章 基本操作", type: "term",
      front: "Rでオブジェクト名の大文字と小文字は区別される？",
      back: "区別される。<code>result</code> と <code>Result</code> は別のオブジェクト" },
    { id: "s01-t06", chapter: "第1章 基本操作", type: "term",
      front: "Rで絶対値を計算する関数は？",
      back: "<code>abs(数値)</code>" },

    { id: "s01-m01", chapter: "第1章 基本操作", type: "mc",
      question: "<code>result &lt;- 5 + 3</code> の後、<code>result &lt;- 5 - 3</code> を実行すると <code>result</code> の値はいくつ？",
      choices: ["2", "8", "エラーになる", "5"],
      answer: 0,
      explanation: "オブジェクトは上書きされる。最後に代入された <code>5 - 3 = 2</code> が保存される。" },
    { id: "s01-m02", chapter: "第1章 基本操作", type: "mc",
      question: "<code>10^20</code> の出力はどう表示される？",
      choices: ["1e+20", "10000000000000000000", "100^10", "Inf"],
      answer: 0,
      explanation: "Rは非常に大きな数を科学的記数法で表示する。<code>e+20</code> は $10^{20}$ を意味する。" },
    { id: "s01-m03", chapter: "第1章 基本操作", type: "mc",
      question: "未定義のオブジェクト <code>Result</code> を参照するとどうなる？",
      choices: ["エラーが出る", "NULLが返る", "NAが返る", "0が返る"],
      answer: 0,
      explanation: "<code>Error: object 'Result' not found</code> というエラーが出る。大文字・小文字は区別される。" },

    // ===== 第2章: ベクトルとデータ型 =====
    { id: "s01-t07", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルを作成する関数の一般形は？",
      back: "<code>c(要素1, 要素2, ...)</code>" },
    { id: "s01-t08", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルの2番目の要素を取り出す書き方は？",
      back: "<code>ベクトル[2]</code>（Rのインデックスは1始まり）" },
    { id: "s01-t09", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルから指定したインデックスの要素を除外する書き方は？",
      back: "<code>ベクトル[-c(i, j)]</code>（マイナスをつける）" },
    { id: "s01-t10", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "等間隔の数列を生成する関数の一般形は？",
      back: "<code>seq(from = 開始, to = 終了, by = 間隔)</code>" },
    { id: "s01-t11", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "1刻みの連続整数を生成する記法は？（例: 2008から2012）",
      back: "<code>2008:2012</code>（コロン演算子）" },
    { id: "s01-t12", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルに名前をつける関数の一般形は？",
      back: "<code>names(ベクトル) &lt;- 名前のベクトル</code>" },
    { id: "s01-t13", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "オブジェクトのデータ型を確認する関数は？",
      back: "<code>class(x)</code>" },
    { id: "s01-t14", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "文字列を数値に変換する関数は？",
      back: "<code>as.numeric(x)</code>" },
    { id: "s01-t15", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "xが数値型かどうかを判定する関数は？",
      back: "<code>is.numeric(x)</code>（TRUEまたはFALSEを返す）" },
    { id: "s01-t16", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "「等しい」を比較する演算子と「等しくない」を比較する演算子は？",
      back: "<code>==</code>（等しい）と <code>!=</code>（等しくない）" },
    { id: "s01-t17", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "Rの主な3つのデータ型は？",
      back: "numeric（数値型）、character（文字型）、logical（論理型: TRUE/FALSE）" },

    { id: "s01-m04", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>c(1, 2, \"a\")</code> の結果はどうなる？",
      choices: ["全て文字型に変換される（\"1\" \"2\" \"a\"）", "エラーになる", "数値と文字が混在したまま保持", "\"a\"がNAになる"],
      answer: 0,
      explanation: "ベクトル内で型が混在すると、自動的に型変換される。数値が文字型に変換される。" },
    { id: "s01-m05", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>\"3.14\" + 1</code> の結果は？",
      choices: ["エラーになる", "4.14", "\"4.14\"", "NA"],
      answer: 0,
      explanation: "文字型と数値型の計算はできない。<code>as.numeric(\"3.14\") + 1</code> なら4.14になる。" },
    { id: "s01-m06", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>x &lt;- c(TRUE, FALSE, TRUE)</code> のとき、<code>mean(x)</code> の結果は？",
      choices: ["0.6666667", "2", "TRUE", "エラーになる"],
      answer: 0,
      explanation: "論理値は数値演算時にTRUE=1, FALSE=0に変換される。(1+0+1)/3 = 0.6667。これはTRUEの割合を表す。" },
    { id: "s01-m07", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>world.pop[c(2, 4)]</code> は何を返す？",
      choices: ["2番目と4番目の要素", "2番目から4番目までの要素", "2番目と4番目を除く全要素", "エラーになる"],
      answer: 0,
      explanation: "<code>c(2, 4)</code> でインデックス2と4を指定し、その位置の要素を取り出す。" },
    { id: "s01-m08", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>\"Hello\" == \"hello\"</code> の結果は？",
      choices: ["FALSE", "TRUE", "エラーになる", "NA"],
      answer: 0,
      explanation: "Rは大文字と小文字を区別する。\"Hello\" と \"hello\" は異なる文字列。" },

    // ===== 第3章: 関数の基本 =====
    { id: "s01-t18", chapter: "第3章 関数の基本", type: "term",
      front: "自作関数を定義する一般形は？",
      back: "<code>関数名 &lt;- function(引数1, 引数2) { 処理; return(出力) }</code>" },
    { id: "s01-t19", chapter: "第3章 関数の基本", type: "term",
      front: "関数のヘルプを表示するコマンドは？",
      back: "<code>?関数名</code>（例: <code>?rep</code>）" },
    { id: "s01-t20", chapter: "第3章 関数の基本", type: "term",
      front: "ベクトルの要素数を返す関数は？",
      back: "<code>length(x)</code>" },
    { id: "s01-t21", chapter: "第3章 関数の基本", type: "term",
      front: "値を繰り返すベクトルを作る関数の一般形は？",
      back: "<code>rep(値, 回数)</code>（例: <code>rep(2, 4)</code> → <code>2 2 2 2</code>）" },
    { id: "s01-t22", chapter: "第3章 関数の基本", type: "term",
      front: "NAを含むベクトルで平均を計算するとき、NAを除外する方法は？",
      back: "<code>mean(x, na.rm = TRUE)</code>" },
    { id: "s01-t23", chapter: "第3章 関数の基本", type: "term",
      front: "標準偏差を計算する関数は？",
      back: "<code>sd(x)</code>（NA除外時: <code>sd(x, na.rm = TRUE)</code>）" },
    { id: "s01-t24", chapter: "第3章 関数の基本", type: "term",
      front: "分散を計算する関数は？",
      back: "<code>var(x)</code>（NA除外時: <code>var(x, na.rm = TRUE)</code>）" },
    { id: "s01-t25", chapter: "第3章 関数の基本", type: "term",
      front: "要約統計量（最小・四分位・最大・平均）を一度に表示する関数は？",
      back: "<code>summary(x)</code>" },
    { id: "s01-t26", chapter: "第3章 関数の基本", type: "term",
      front: "自然対数を計算する関数は？底は何？",
      back: "<code>log(x)</code>。底はネイピア数 $e = 2.71828...$" },

    { id: "s01-m09", chapter: "第3章 関数の基本", type: "mc",
      question: "デフォルト引数付きの関数定義で正しいのは？",
      choices: [
        "<code>f &lt;- function(x, y = 5) { return(x - y) }</code>",
        "<code>f &lt;- function(x, y := 5) { return(x - y) }</code>",
        "<code>f &lt;- function(x, default y = 5) { return(x - y) }</code>",
        "<code>f &lt;- function(x, y) = 5 { return(x - y) }</code>"
      ],
      answer: 0,
      explanation: "デフォルト値は引数リスト内で <code>=</code> で指定する。<code>f(1)</code> とすると <code>y = 5</code> がデフォルトで使われる。" },
    { id: "s01-m10", chapter: "第3章 関数の基本", type: "mc",
      question: "<code>mean(c(1, 2, NA))</code> の結果は？",
      choices: ["NA", "1.5", "1", "エラーになる"],
      answer: 0,
      explanation: "NAを含むベクトルにそのままmean()を適用すると結果もNAになる。<code>na.rm = TRUE</code> を指定すれば1.5になる。" },
    { id: "s01-m11", chapter: "第3章 関数の基本", type: "mc",
      question: "<code>my.diff &lt;- function(a, b) { return(a - b) }</code> を定義後、<code>my.diff(b = 3, a = 1)</code> の結果は？",
      choices: ["-2", "2", "エラーになる", "NA"],
      answer: 0,
      explanation: "引数名を指定すれば順序は自由。<code>a = 1, b = 3</code> なので <code>1 - 3 = -2</code>。" },

    // ===== 第4章: データフレーム操作 =====
    { id: "s02-t01", chapter: "第4章 データフレーム操作", type: "term",
      front: "CSVファイルをtidyverseで読み込む関数の一般形は？",
      back: "<code>データ名 &lt;- read_csv(\"ファイルパス.csv\")</code>" },
    { id: "s02-t02", chapter: "第4章 データフレーム操作", type: "term",
      front: "パッケージをインストールする関数と読み込む関数は？",
      back: "<code>install.packages(\"パッケージ名\")</code>（初回のみ）と <code>library(パッケージ名)</code>（毎回）" },
    { id: "s02-t03", chapter: "第4章 データフレーム操作", type: "term",
      front: "パイプ演算子 <code>|&gt;</code> の意味は？",
      back: "左側のオブジェクトを右側の関数の第1引数に渡す。<code>x |&gt; f()</code> は <code>f(x)</code> と同じ" },
    { id: "s02-t04", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームから行を条件で選択する関数は？",
      back: "<code>filter(条件式)</code>（例: <code>filter(race == \"black\")</code>）" },
    { id: "s02-t05", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームから列を選択する関数は？除外する方法は？",
      back: "<code>select(列名1, 列名2)</code> で選択。<code>select(-c(列名1, 列名2))</code> で除外" },
    { id: "s02-t06", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームに新しい列を追加・変換する関数は？",
      back: "<code>mutate(新列名 = 計算式)</code>" },
    { id: "s02-t07", chapter: "第4章 データフレーム操作", type: "term",
      front: "条件に基づいて値を選択するifelse関数の一般形は？",
      back: "<code>ifelse(条件, TRUEのときの値, FALSEのときの値)</code>" },
    { id: "s02-t08", chapter: "第4章 データフレーム操作", type: "term",
      front: "横型データを縦型（ロング形式）に変換する関数の一般形は？",
      back: "<code>pivot_longer(cols = 列指定, names_to = \"列名\", values_to = \"値列名\")</code>" },
    { id: "s02-t09", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームの列名を確認・変更する方法は？",
      back: "<code>colnames(データ)</code> で確認。<code>colnames(データ) &lt;- 新しい名前のベクトル</code> で変更" },
    { id: "s02-t10", chapter: "第4章 データフレーム操作", type: "term",
      front: "列をベクトルとして取り出すtidyverse関数は？Base Rの書き方は？",
      back: "<code>pull(列名)</code>。Base Rでは <code>データ$列名</code>" },
    { id: "s02-t11", chapter: "第4章 データフレーム操作", type: "term",
      front: "重複を除いた一意な値を確認する関数は？",
      back: "<code>distinct(列名)</code>" },
    { id: "s02-t12", chapter: "第4章 データフレーム操作", type: "term",
      front: "データを昇順に並び替える関数は？",
      back: "<code>arrange(列名)</code>（降順は <code>arrange(desc(列名))</code>）" },

    { id: "s02-m01", chapter: "第4章 データフレーム操作", type: "mc",
      question: "<code>x |&gt; f() |&gt; g()</code> をパイプなしで書くとどうなる？",
      choices: ["g(f(x))", "f(g(x))", "f(x, g())", "g(x, f())"],
      answer: 0,
      explanation: "パイプは左から右に流れる。<code>x |&gt; f()</code> = <code>f(x)</code>、その結果が <code>g()</code> に渡される。" },
    { id: "s02-m02", chapter: "第4章 データフレーム操作", type: "mc",
      question: "<code>filter(race == \"black\" & sex == \"female\")</code> はどのような行を選択する？",
      choices: ["raceが\"black\"かつsexが\"female\"の行", "raceが\"black\"またはsexが\"female\"の行", "raceが\"black\"の行だけ", "エラーになる"],
      answer: 0,
      explanation: "<code>&</code> は「かつ」（AND）を意味する。両方の条件を同時に満たす行のみが選択される。" },
    { id: "s02-m03", chapter: "第4章 データフレーム操作", type: "mc",
      question: "2つのデータフレームを共通の列で結合し、一致する行のみを残す関数は？",
      choices: ["inner_join()", "left_join()", "full_join()", "merge()"],
      answer: 0,
      explanation: "<code>inner_join(x, y, by = \"列名\")</code> は共通の値が一致する行のみを結合する。" },
    { id: "s02-m04", chapter: "第4章 データフレーム操作", type: "mc",
      question: "CSVとRDSの違いについて正しいのは？",
      choices: ["CSVは型情報を保持しないが、RDSは型情報を保持する", "CSVの方がRDSよりサイズが小さい", "RDSは他のプログラムで読めるがCSVは読めない", "両者に違いはない"],
      answer: 0,
      explanation: "CSVはテキスト形式で型情報が失われる。RDSはバイナリ形式でデータ型を保持し、サイズも小さい。" },
    { id: "s02-m05", chapter: "第4章 データフレーム操作", type: "mc",
      question: "<code>filter(列名 %in% c(\"A\", \"B\", \"C\"))</code> はどういう意味？",
      choices: ["列名の値が\"A\"、\"B\"、\"C\"のいずれかに一致する行を選択", "列名の値が\"A\"、\"B\"、\"C\"の全てに一致する行を選択", "列名から\"A\"、\"B\"、\"C\"を除外", "列\"A\"、\"B\"、\"C\"を選択"],
      answer: 0,
      explanation: "<code>%in%</code> は「いずれかに含まれる」を意味し、複数の値でOR条件をまとめて書ける。" },

    // ===== 第5章: データ集計 =====
    { id: "s02-t13", chapter: "第5章 データ集計", type: "term",
      front: "グループ別に集計する基本パターン（一般形）は？",
      back: "<code>データ |&gt; group_by(グループ列) |&gt; summarize(新列名 = 集計関数(列名))</code>" },
    { id: "s02-t14", chapter: "第5章 データ集計", type: "term",
      front: "ダミー変数（0/1）の平均値が表す意味は？",
      back: "条件を満たすデータの割合。$\\bar{x} = \\frac{k}{n}$（$k$ はダミー=1の個数、$n$ は全データ数）" },
    { id: "s02-t15", chapter: "第5章 データ集計", type: "term",
      front: "クロス集計表を作成する一般形は？",
      back: "<code>データ |&gt; select(列名1, 列名2) |&gt; table()</code>" },
    { id: "s02-t16", chapter: "第5章 データ集計", type: "term",
      front: "クロス集計表に行・列の合計を追加する関数は？比率に変換する関数は？",
      back: "<code>addmargins(集計表)</code> と <code>prop.table(集計表)</code>" },
    { id: "s02-t17", chapter: "第5章 データ集計", type: "term",
      front: "table()でNAも集計に含めるにはどうする？",
      back: "<code>table(exclude = NULL)</code>" },
    { id: "s02-t18", chapter: "第5章 データ集計", type: "term",
      front: "指定した分位数を計算する関数の一般形は？",
      back: "<code>quantile(x, probs = 確率ベクトル, na.rm = TRUE)</code>" },
    { id: "s02-t19", chapter: "第5章 データ集計", type: "term",
      front: "十分位数を計算するときのprobs引数の指定は？",
      back: "<code>probs = seq(0, 1, by = 0.1)</code>" },
    { id: "s02-t20", chapter: "第5章 データ集計", type: "term",
      front: "複数列に一括で同じ関数を適用する関数は？",
      back: "<code>sapply(関数名, 追加引数...)</code>" },
    { id: "s02-t21", chapter: "第5章 データ集計", type: "term",
      front: "ある列がNAである割合を計算するコードは？",
      back: "<code>mean(is.na(列名))</code>" },

    { id: "s02-m06", chapter: "第5章 データ集計", type: "mc",
      question: "<code>resume |&gt; group_by(race) |&gt; summarize(call_rate = mean(call))</code> は何を計算する？",
      choices: ["race別のcallの平均値（＝通過率）", "race列の要素数", "全体のcallの平均値", "race別のcallの合計値"],
      answer: 0,
      explanation: "<code>group_by(race)</code> でrace別にグループ化し、各グループで <code>mean(call)</code> を計算。callがダミー変数(0/1)なので平均=割合。" },
    { id: "s02-m07", chapter: "第5章 データ集計", type: "mc",
      question: "<code>mean(wageBefore < 5.05)</code> は何を計算する？",
      choices: ["wageBeforeが5.05未満の割合", "wageBeforeの平均が5.05未満かどうか", "5.05未満のwageBeforeの平均", "wageBeforeから5.05を引いた平均"],
      answer: 0,
      explanation: "<code>wageBefore < 5.05</code> は各要素がTRUE/FALSEの論理ベクトルを返す。<code>mean()</code> でTRUEの割合を計算する。" },
    { id: "s02-m08", chapter: "第5章 データ集計", type: "mc",
      question: "<code>table()</code> のデフォルトの動作として正しいのは？",
      choices: ["NAを無視して集計する", "NAも集計に含める", "NAがあるとエラーになる", "NAを0として扱う"],
      answer: 0,
      explanation: "<code>table()</code> はデフォルトでNAを無視する。NAも含めるには <code>table(exclude = NULL)</code> を使う。" },

    { id: "s02-e01", chapter: "第5章 データ集計", type: "essay",
      question: "差の差分法（DID）の手順をRコードの一般形で説明せよ。",
      modelAnswer: "差の差分法は3ステップで行う。<br>①介入群・コントロール群ごとに、介入前後の測定値の平均を計算する：<code>データ |&gt; group_by(グループ列) |&gt; summarize(前 = mean(前列), 後 = mean(後列))</code><br>②各群の前後差を計算する：<code>mutate(diff = 後 - 前)</code><br>③介入群の差からコントロール群の差を引く：<code>diff[1] - diff[2]</code><br>これにより、時間の経過による共通の変化を取り除いた、介入の純粋な因果効果を推定できる。",
      points: ["group_by + summarize で群別に前後の平均を計算", "mutateで前後差を算出", "2群の差の差を計算して因果効果を推定"] },

    // ===== 第6章: ggplotによるグラフ作成 =====
    { id: "s03-t01", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotの基本構造（一般形）は？",
      back: "<code>データ |&gt; ggplot(aes(x = 列名, y = 列名)) + geom_xxx() + labs() + theme_minimal()</code>" },
    { id: "s03-t02", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで棒グラフを描く関数は？y軸の値をそのまま使うには？",
      back: "<code>geom_bar(stat = \"identity\")</code>" },
    { id: "s03-t03", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotでヒストグラムを描く関数は？ビンの幅と密度の指定方法は？",
      back: "<code>geom_histogram(binwidth = 幅, boundary = 境界値)</code>。密度は <code>aes(y = after_stat(density))</code>" },
    { id: "s03-t04", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで箱ひげ図を描く関数は？",
      back: "<code>geom_boxplot(fill = \"色\", outlier.shape = 形状, outlier.size = サイズ)</code>" },
    { id: "s03-t05", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで散布図を描く関数は？",
      back: "<code>geom_point(size = サイズ, alpha = 透明度)</code>" },
    { id: "s03-t06", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで線グラフを描く関数は？",
      back: "<code>geom_line(linewidth = 太さ)</code>" },
    { id: "s03-t07", chapter: "第6章 ggplotグラフ", type: "term",
      front: "グラフのタイトルと軸ラベルを設定する関数の一般形は？",
      back: "<code>labs(x = \"x軸\", y = \"y軸\", title = \"タイトル\")</code>" },
    { id: "s03-t08", chapter: "第6章 ggplotグラフ", type: "term",
      front: "グラフを画像として保存する関数は？",
      back: "<code>ggsave(\"フォルダ/ファイル名.png\")</code>" },
    { id: "s03-t09", chapter: "第6章 ggplotグラフ", type: "term",
      front: "散布図でグループごとに色と形状を分ける方法は？",
      back: "<code>aes(color = グループ列, shape = グループ列)</code> で指定" },
    { id: "s03-t10", chapter: "第6章 ggplotグラフ", type: "term",
      front: "色を手動で指定する関数の一般形は？",
      back: "<code>scale_color_manual(name = \"凡例\", values = c(\"値\" = \"色コード\", ...))</code>" },

    { id: "s03-m01", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "ggplotの各レイヤーを繋ぐ記号は？",
      choices: ["+（プラス記号）", "|>（パイプ演算子）", "&（アンパサンド）", ">>（二重矢印）"],
      answer: 0,
      explanation: "ggplotのレイヤーは <code>+</code> で繋ぐ。パイプ <code>|&gt;</code> はデータをggplotに渡すときに使うが、ggplot内部のレイヤー結合には <code>+</code>。" },
    { id: "s03-m02", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "ヒストグラムでy軸を密度にするための指定は？",
      choices: ["aes(y = after_stat(density))", "aes(y = density)", "geom_histogram(density = TRUE)", "scale_y_density()"],
      answer: 0,
      explanation: "<code>after_stat(density)</code> で統計変換後の密度値をy軸に使用する。" },
    { id: "s03-m03", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "箱ひげ図が表現する5つの要約統計量は？",
      choices: ["最小値・Q1・中央値・Q3・最大値", "平均・標準偏差・最小・最大・中央値", "Q1・Q2・Q3・Q4・平均", "最小値・平均・中央値・最頻値・最大値"],
      answer: 0,
      explanation: "箱ひげ図は最小値、第1四分位数(Q1)、中央値(Q2)、第3四分位数(Q3)、最大値の5つを表現する。" },
    { id: "s03-m04", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "散布図で点が重なって見づらいとき、有効な対策は？",
      choices: ["alpha（透明度）を下げる", "点のサイズを大きくする", "軸の範囲を狭める", "線グラフに変更する"],
      answer: 0,
      explanation: "透明度(alpha)を下げると、点が重なっている部分が濃くなり、密度を視覚的に表現できる。サイズを小さくすることも有効。" },

    // ===== 第7章: 統計分析 =====
    { id: "s03-t11", chapter: "第7章 統計分析", type: "term",
      front: "2変数の相関係数を計算する関数の一般形は？",
      back: "<code>cor(x, y)</code> または <code>データ |&gt; summarise(r = cor(列名1, 列名2))</code>" },
    { id: "s03-t12", chapter: "第7章 統計分析", type: "term",
      front: "Q-Qプロットを作成する関数の一般形は？",
      back: "<code>qqplot(ベクトル1, ベクトル2, xlab = \"x軸\", ylab = \"y軸\")</code>" },
    { id: "s03-t13", chapter: "第7章 統計分析", type: "term",
      front: "Q-Qプロットに45度線を追加するコードは？",
      back: "<code>abline(0, 1)</code>（切片0、傾き1の直線）" },
    { id: "s03-t14", chapter: "第7章 統計分析", type: "term",
      front: "$k$平均法を実行する関数の一般形は？",
      back: "<code>kmeans(データ, centers = k, nstart = 試行回数)</code>" },
    { id: "s03-t15", chapter: "第7章 統計分析", type: "term",
      front: "$k$平均法の結果からクラスター中心点を確認する方法は？",
      back: "<code>結果$centers</code>" },
    { id: "s03-t16", chapter: "第7章 統計分析", type: "term",
      front: "$k$平均法の結果から各データのクラスター番号を確認する方法は？",
      back: "<code>結果$cluster</code>" },
    { id: "s03-t17", chapter: "第7章 統計分析", type: "term",
      front: "自然対数変換の数学的性質として、対数の差は何に近似できる？",
      back: "$\\log(x_2) - \\log(x_1) = \\log\\left(\\frac{x_2}{x_1}\\right) \\approx \\frac{x_2 - x_1}{x_1}$（変化率に近似）" },

    { id: "s03-m05", chapter: "第7章 統計分析", type: "mc",
      question: "$k$平均法のクラスター番号について正しいのは？",
      choices: ["番号に意味はなく、実行のたびに変わりうる", "常にクラスター1が最大のクラスター", "番号が小さいほど中心に近い", "番号は政党に対応する"],
      answer: 0,
      explanation: "クラスター番号は任意であり、意味はない。実行のたびに初期値が異なるため番号が変わりうる。" },
    { id: "s03-m06", chapter: "第7章 統計分析", type: "mc",
      question: "Q-Qプロットで点が45度線の上にある場合、何を意味する？",
      choices: ["y軸側（縦軸）の変数の値が大きい", "x軸側（横軸）の変数の値が大きい", "2つの分布が同じ", "外れ値がある"],
      answer: 0,
      explanation: "45度線より上にある点は、y軸に対応する変数の分位数がx軸に対応する変数の分位数よりも大きいことを示す。" },
    { id: "s03-m07", chapter: "第7章 統計分析", type: "mc",
      question: "<code>log(0)</code> の結果は？",
      choices: ["-Inf", "0", "NA", "エラーになる"],
      answer: 0,
      explanation: "$\\log(0) = -\\infty$ なので、Rでは <code>-Inf</code> を返す。負の値の場合は <code>NaN</code> を返す。" },
    { id: "s03-m08", chapter: "第7章 統計分析", type: "mc",
      question: "対数変換が有効なのはどのような場合？",
      choices: ["データの分布が右に大きく偏っているとき", "データが正規分布に従うとき", "データに負の値が多いとき", "データの平均が0に近いとき"],
      answer: 0,
      explanation: "収入や人口のように右に偏った分布に対数変換を行うと、偏りが修正されより対称的な分布になる。ただし0や負の値には適用不可。" },

    { id: "s03-e01", chapter: "第7章 統計分析", type: "essay",
      question: "$k$平均法のアルゴリズムの手順を4つのステップで説明せよ。",
      modelAnswer: "①$k$個のクラスターの初期中心点を（ランダムに）選択する。<br>②各データ点を、最も近い中心点を持つクラスターに割り当てる（ユークリッド距離で判定）。<br>③各クラスターの新しい中心点を、そのクラスターに属する全データ点の平均座標として計算する。<br>④クラスターへの割り当てが変化しなくなるまで②と③を繰り返す。<br>Rでは <code>kmeans(データ, centers = k, nstart = 試行回数)</code> で実行する。<code>nstart</code>で複数の初期値を試し、最良の結果を選ぶ。",
      points: ["初期中心点のランダム選択", "各点を最近接クラスターに割り当て→中心点再計算の繰り返し", "収束条件（割り当てが変化しなくなるまで）"] },
    { id: "s03-e02", chapter: "第6章 ggplotグラフ", type: "essay",
      question: "ggplotで散布図を作成し、グループごとに色と形状を分けて、軸ラベルとタイトルを設定する完全なコードの一般形を書け。",
      modelAnswer: "<code>データ |&gt;<br>&nbsp;&nbsp;ggplot(aes(x = 列名1, y = 列名2, color = グループ列, shape = グループ列)) +<br>&nbsp;&nbsp;geom_point(size = サイズ, alpha = 透明度) +<br>&nbsp;&nbsp;scale_color_manual(name = \"凡例\", values = c(\"値1\" = \"色1\", \"値2\" = \"色2\")) +<br>&nbsp;&nbsp;scale_shape_manual(name = \"凡例\", values = c(\"値1\" = 16, \"値2\" = 17)) +<br>&nbsp;&nbsp;labs(x = \"x軸ラベル\", y = \"y軸ラベル\", title = \"タイトル\") +<br>&nbsp;&nbsp;theme_minimal(base_family = \"フォント名\")</code>",
      points: ["aes()でcolor, shapeにグループ変数を指定", "scale_color_manual / scale_shape_manual で色と形を手動設定", "labs()でラベルとタイトルを設定し、theme_minimal()でテーマ適用"] }
  ]
};
