window.QUIZ_DATA = {
  id: "統計学1_期末",
  title: "統計学1 期末 Rコード一般形",
  questions: [
    // ===== 第1章: 基本操作 =====
    { id: "s01-t01", chapter: "第1章 基本操作", type: "term",
      front: "Rで計算結果をオブジェクトに保存するときに使う演算子の書き方は？",
      back: "<code>オブジェクト名 &lt;- 値</code>（代入演算子 <code>&lt;-</code> を使う）" },
    { id: "s01-t02", chapter: "第1章 基本操作", type: "term",
      front: "Rでコメントを書くための記号は？",
      back: "<code>#</code>（シャープ記号以降がコメントになり、実行されない）" },
    { id: "s01-t03", chapter: "第1章 基本操作", type: "term",
      front: "Rで平方根を計算する関数は？",
      back: "<code>sqrt(数値)</code>" },
    { id: "s01-t04", chapter: "第1章 基本操作", type: "term",
      front: "Rでべき乗を計算する演算子は？",
      back: "<code>^</code>（例: <code>5 ^ 3</code> → 125）" },
    { id: "s01-t05", chapter: "第1章 基本操作", type: "term",
      front: "Rでオブジェクト名の大文字と小文字は区別される？",
      back: "区別される。<code>result</code> と <code>Result</code> は別のオブジェクト" },
    { id: "s01-t06", chapter: "第1章 基本操作", type: "term",
      front: "Rで絶対値を計算する関数は？",
      back: "<code>abs(数値)</code>" },

    { id: "s01-m01", chapter: "第1章 基本操作", type: "mc",
      question: "<code>result &lt;- 5 + 3</code> の後、<code>result &lt;- 5 - 3</code> を実行すると <code>result</code> の値はいくつ？",
      choices: ["2", "8", "エラーになる", "5"],
      answer: 0,
      explanation: "オブジェクトは上書きされる。最後に代入された <code>5 - 3 = 2</code> が保存される。" },
    { id: "s01-m02", chapter: "第1章 基本操作", type: "mc",
      question: "<code>10^20</code> の出力はどう表示される？",
      choices: ["1e+20", "10000000000000000000", "100^10", "Inf"],
      answer: 0,
      explanation: "Rは非常に大きな数を科学的記数法で表示する。<code>e+20</code> は $10^{20}$ を意味する。" },
    { id: "s01-m03", chapter: "第1章 基本操作", type: "mc",
      question: "未定義のオブジェクト <code>Result</code> を参照するとどうなる？",
      choices: ["エラーが出る", "NULLが返る", "NAが返る", "0が返る"],
      answer: 0,
      explanation: "<code>Error: object 'Result' not found</code> というエラーが出る。大文字・小文字は区別される。" },

    // ===== 第2章: ベクトルとデータ型 =====
    { id: "s01-t07", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルを作成する関数の一般形は？",
      back: "<code>c(要素1, 要素2, ...)</code>" },
    { id: "s01-t08", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルの2番目の要素を取り出す書き方は？",
      back: "<code>ベクトル[2]</code>（Rのインデックスは1始まり）" },
    { id: "s01-t09", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルから指定したインデックスの要素を除外する書き方は？",
      back: "<code>ベクトル[-c(i, j)]</code>（マイナスをつける）" },
    { id: "s01-t10", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "等間隔の数列を生成する関数の一般形は？",
      back: "<code>seq(from = 開始, to = 終了, by = 間隔)</code>" },
    { id: "s01-t11", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "1刻みの連続整数を生成する記法は？（例: 2008から2012）",
      back: "<code>2008:2012</code>（コロン演算子）" },
    { id: "s01-t12", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "ベクトルに名前をつける関数の一般形は？",
      back: "<code>names(ベクトル) &lt;- 名前のベクトル</code>" },
    { id: "s01-t13", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "オブジェクトのデータ型を確認する関数は？",
      back: "<code>class(x)</code>" },
    { id: "s01-t14", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "文字列を数値に変換する関数は？",
      back: "<code>as.numeric(x)</code>" },
    { id: "s01-t15", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "xが数値型かどうかを判定する関数は？",
      back: "<code>is.numeric(x)</code>（TRUEまたはFALSEを返す）" },
    { id: "s01-t16", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "「等しい」を比較する演算子と「等しくない」を比較する演算子は？",
      back: "<code>==</code>（等しい）と <code>!=</code>（等しくない）" },
    { id: "s01-t17", chapter: "第2章 ベクトルとデータ型", type: "term",
      front: "Rの主な3つのデータ型は？",
      back: "numeric（数値型）、character（文字型）、logical（論理型: TRUE/FALSE）" },

    { id: "s01-m04", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>c(1, 2, \"a\")</code> の結果はどうなる？",
      choices: ["全て文字型に変換される（\"1\" \"2\" \"a\"）", "エラーになる", "数値と文字が混在したまま保持", "\"a\"がNAになる"],
      answer: 0,
      explanation: "ベクトル内で型が混在すると、自動的に型変換される。数値が文字型に変換される。" },
    { id: "s01-m05", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>\"3.14\" + 1</code> の結果は？",
      choices: ["エラーになる", "4.14", "\"4.14\"", "NA"],
      answer: 0,
      explanation: "文字型と数値型の計算はできない。<code>as.numeric(\"3.14\") + 1</code> なら4.14になる。" },
    { id: "s01-m06", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>x &lt;- c(TRUE, FALSE, TRUE)</code> のとき、<code>mean(x)</code> の結果は？",
      choices: ["0.6666667", "2", "TRUE", "エラーになる"],
      answer: 0,
      explanation: "論理値は数値演算時にTRUE=1, FALSE=0に変換される。(1+0+1)/3 = 0.6667。これはTRUEの割合を表す。" },
    { id: "s01-m07", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>world.pop[c(2, 4)]</code> は何を返す？",
      choices: ["2番目と4番目の要素", "2番目から4番目までの要素", "2番目と4番目を除く全要素", "エラーになる"],
      answer: 0,
      explanation: "<code>c(2, 4)</code> でインデックス2と4を指定し、その位置の要素を取り出す。" },
    { id: "s01-m08", chapter: "第2章 ベクトルとデータ型", type: "mc",
      question: "<code>\"Hello\" == \"hello\"</code> の結果は？",
      choices: ["FALSE", "TRUE", "エラーになる", "NA"],
      answer: 0,
      explanation: "Rは大文字と小文字を区別する。\"Hello\" と \"hello\" は異なる文字列。" },

    // ===== 第3章: 関数の基本 =====
    { id: "s01-t18", chapter: "第3章 関数の基本", type: "term",
      front: "自作関数を定義する一般形は？",
      back: "<code>関数名 &lt;- function(引数1, 引数2) { 処理; return(出力) }</code>" },
    { id: "s01-t19", chapter: "第3章 関数の基本", type: "term",
      front: "関数のヘルプを表示するコマンドは？",
      back: "<code>?関数名</code>（例: <code>?rep</code>）" },
    { id: "s01-t20", chapter: "第3章 関数の基本", type: "term",
      front: "ベクトルの要素数を返す関数は？",
      back: "<code>length(x)</code>" },
    { id: "s01-t21", chapter: "第3章 関数の基本", type: "term",
      front: "値を繰り返すベクトルを作る関数の一般形は？",
      back: "<code>rep(値, 回数)</code>（例: <code>rep(2, 4)</code> → <code>2 2 2 2</code>）" },
    { id: "s01-t22", chapter: "第3章 関数の基本", type: "term",
      front: "NAを含むベクトルで平均を計算するとき、NAを除外する方法は？",
      back: "<code>mean(x, na.rm = TRUE)</code>" },
    { id: "s01-t23", chapter: "第3章 関数の基本", type: "term",
      front: "標準偏差を計算する関数は？",
      back: "<code>sd(x)</code>（NA除外時: <code>sd(x, na.rm = TRUE)</code>）" },
    { id: "s01-t24", chapter: "第3章 関数の基本", type: "term",
      front: "分散を計算する関数は？",
      back: "<code>var(x)</code>（NA除外時: <code>var(x, na.rm = TRUE)</code>）" },
    { id: "s01-t25", chapter: "第3章 関数の基本", type: "term",
      front: "要約統計量（最小・四分位・最大・平均）を一度に表示する関数は？",
      back: "<code>summary(x)</code>" },
    { id: "s01-t26", chapter: "第3章 関数の基本", type: "term",
      front: "自然対数を計算する関数は？底は何？",
      back: "<code>log(x)</code>。底はネイピア数 $e = 2.71828...$" },

    { id: "s01-m09", chapter: "第3章 関数の基本", type: "mc",
      question: "デフォルト引数付きの関数定義で正しいのは？",
      choices: [
        "<code>f &lt;- function(x, y = 5) { return(x - y) }</code>",
        "<code>f &lt;- function(x, y := 5) { return(x - y) }</code>",
        "<code>f &lt;- function(x, default y = 5) { return(x - y) }</code>",
        "<code>f &lt;- function(x, y) = 5 { return(x - y) }</code>"
      ],
      answer: 0,
      explanation: "デフォルト値は引数リスト内で <code>=</code> で指定する。<code>f(1)</code> とすると <code>y = 5</code> がデフォルトで使われる。" },
    { id: "s01-m10", chapter: "第3章 関数の基本", type: "mc",
      question: "<code>mean(c(1, 2, NA))</code> の結果は？",
      choices: ["NA", "1.5", "1", "エラーになる"],
      answer: 0,
      explanation: "NAを含むベクトルにそのままmean()を適用すると結果もNAになる。<code>na.rm = TRUE</code> を指定すれば1.5になる。" },
    { id: "s01-m11", chapter: "第3章 関数の基本", type: "mc",
      question: "<code>my.diff &lt;- function(a, b) { return(a - b) }</code> を定義後、<code>my.diff(b = 3, a = 1)</code> の結果は？",
      choices: ["-2", "2", "エラーになる", "NA"],
      answer: 0,
      explanation: "引数名を指定すれば順序は自由。<code>a = 1, b = 3</code> なので <code>1 - 3 = -2</code>。" },

    // ===== 第4章: データフレーム操作 =====
    { id: "s02-t01", chapter: "第4章 データフレーム操作", type: "term",
      front: "CSVファイルをtidyverseで読み込む関数の一般形は？",
      back: "<code>データ名 &lt;- read_csv(\"ファイルパス.csv\")</code>" },
    { id: "s02-t02", chapter: "第4章 データフレーム操作", type: "term",
      front: "パッケージをインストールする関数と読み込む関数は？",
      back: "<code>install.packages(\"パッケージ名\")</code>（初回のみ）と <code>library(パッケージ名)</code>（毎回）" },
    { id: "s02-t03", chapter: "第4章 データフレーム操作", type: "term",
      front: "パイプ演算子 <code>|&gt;</code> の意味は？",
      back: "左側のオブジェクトを右側の関数の第1引数に渡す。<code>x |&gt; f()</code> は <code>f(x)</code> と同じ" },
    { id: "s02-t04", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームから行を条件で選択する関数は？",
      back: "<code>filter(条件式)</code>（例: <code>filter(race == \"black\")</code>）" },
    { id: "s02-t05", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームから列を選択する関数は？除外する方法は？",
      back: "<code>select(列名1, 列名2)</code> で選択。<code>select(-c(列名1, 列名2))</code> で除外" },
    { id: "s02-t06", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームに新しい列を追加・変換する関数は？",
      back: "<code>mutate(新列名 = 計算式)</code>" },
    { id: "s02-t07", chapter: "第4章 データフレーム操作", type: "term",
      front: "条件に基づいて値を選択するifelse関数の一般形は？",
      back: "<code>ifelse(条件, TRUEのときの値, FALSEのときの値)</code>" },
    { id: "s02-t08", chapter: "第4章 データフレーム操作", type: "term",
      front: "横型データを縦型（ロング形式）に変換する関数の一般形は？",
      back: "<code>pivot_longer(cols = 列指定, names_to = \"列名\", values_to = \"値列名\")</code>" },
    { id: "s02-t09", chapter: "第4章 データフレーム操作", type: "term",
      front: "データフレームの列名を確認・変更する方法は？",
      back: "<code>colnames(データ)</code> で確認。<code>colnames(データ) &lt;- 新しい名前のベクトル</code> で変更" },
    { id: "s02-t10", chapter: "第4章 データフレーム操作", type: "term",
      front: "列をベクトルとして取り出すtidyverse関数は？Base Rの書き方は？",
      back: "<code>pull(列名)</code>。Base Rでは <code>データ$列名</code>" },
    { id: "s02-t11", chapter: "第4章 データフレーム操作", type: "term",
      front: "重複を除いた一意な値を確認する関数は？",
      back: "<code>distinct(列名)</code>" },
    { id: "s02-t12", chapter: "第4章 データフレーム操作", type: "term",
      front: "データを昇順に並び替える関数は？",
      back: "<code>arrange(列名)</code>（降順は <code>arrange(desc(列名))</code>）" },

    { id: "s02-m01", chapter: "第4章 データフレーム操作", type: "mc",
      question: "<code>x |&gt; f() |&gt; g()</code> をパイプなしで書くとどうなる？",
      choices: ["g(f(x))", "f(g(x))", "f(x, g())", "g(x, f())"],
      answer: 0,
      explanation: "パイプは左から右に流れる。<code>x |&gt; f()</code> = <code>f(x)</code>、その結果が <code>g()</code> に渡される。" },
    { id: "s02-m02", chapter: "第4章 データフレーム操作", type: "mc",
      question: "<code>filter(race == \"black\" & sex == \"female\")</code> はどのような行を選択する？",
      choices: ["raceが\"black\"かつsexが\"female\"の行", "raceが\"black\"またはsexが\"female\"の行", "raceが\"black\"の行だけ", "エラーになる"],
      answer: 0,
      explanation: "<code>&</code> は「かつ」（AND）を意味する。両方の条件を同時に満たす行のみが選択される。" },
    { id: "s02-m03", chapter: "第4章 データフレーム操作", type: "mc",
      question: "2つのデータフレームを共通の列で結合し、一致する行のみを残す関数は？",
      choices: ["inner_join()", "left_join()", "full_join()", "merge()"],
      answer: 0,
      explanation: "<code>inner_join(x, y, by = \"列名\")</code> は共通の値が一致する行のみを結合する。" },
    { id: "s02-m04", chapter: "第4章 データフレーム操作", type: "mc",
      question: "CSVとRDSの違いについて正しいのは？",
      choices: ["CSVは型情報を保持しないが、RDSは型情報を保持する", "CSVの方がRDSよりサイズが小さい", "RDSは他のプログラムで読めるがCSVは読めない", "両者に違いはない"],
      answer: 0,
      explanation: "CSVはテキスト形式で型情報が失われる。RDSはバイナリ形式でデータ型を保持し、サイズも小さい。" },
    { id: "s02-m05", chapter: "第4章 データフレーム操作", type: "mc",
      question: "<code>filter(列名 %in% c(\"A\", \"B\", \"C\"))</code> はどういう意味？",
      choices: ["列名の値が\"A\"、\"B\"、\"C\"のいずれかに一致する行を選択", "列名の値が\"A\"、\"B\"、\"C\"の全てに一致する行を選択", "列名から\"A\"、\"B\"、\"C\"を除外", "列\"A\"、\"B\"、\"C\"を選択"],
      answer: 0,
      explanation: "<code>%in%</code> は「いずれかに含まれる」を意味し、複数の値でOR条件をまとめて書ける。" },

    // ===== 第5章: データ集計 =====
    { id: "s02-t13", chapter: "第5章 データ集計", type: "term",
      front: "グループ別に集計する基本パターン（一般形）は？",
      back: "<code>データ |&gt; group_by(グループ列) |&gt; summarize(新列名 = 集計関数(列名))</code>" },
    { id: "s02-t14", chapter: "第5章 データ集計", type: "term",
      front: "ダミー変数（0/1）の平均値が表す意味は？",
      back: "条件を満たすデータの割合。$\\bar{x} = \\frac{k}{n}$（$k$ はダミー=1の個数、$n$ は全データ数）" },
    { id: "s02-t15", chapter: "第5章 データ集計", type: "term",
      front: "クロス集計表を作成する一般形は？",
      back: "<code>データ |&gt; select(列名1, 列名2) |&gt; table()</code>" },
    { id: "s02-t16", chapter: "第5章 データ集計", type: "term",
      front: "クロス集計表に行・列の合計を追加する関数は？比率に変換する関数は？",
      back: "<code>addmargins(集計表)</code> と <code>prop.table(集計表)</code>" },
    { id: "s02-t17", chapter: "第5章 データ集計", type: "term",
      front: "table()でNAも集計に含めるにはどうする？",
      back: "<code>table(exclude = NULL)</code>" },
    { id: "s02-t18", chapter: "第5章 データ集計", type: "term",
      front: "指定した分位数を計算する関数の一般形は？",
      back: "<code>quantile(x, probs = 確率ベクトル, na.rm = TRUE)</code>" },
    { id: "s02-t19", chapter: "第5章 データ集計", type: "term",
      front: "十分位数を計算するときのprobs引数の指定は？",
      back: "<code>probs = seq(0, 1, by = 0.1)</code>" },
    { id: "s02-t20", chapter: "第5章 データ集計", type: "term",
      front: "複数列に一括で同じ関数を適用する関数は？",
      back: "<code>sapply(関数名, 追加引数...)</code>" },
    { id: "s02-t21", chapter: "第5章 データ集計", type: "term",
      front: "ある列がNAである割合を計算するコードは？",
      back: "<code>mean(is.na(列名))</code>" },

    { id: "s02-m06", chapter: "第5章 データ集計", type: "mc",
      question: "<code>resume |&gt; group_by(race) |&gt; summarize(call_rate = mean(call))</code> は何を計算する？",
      choices: ["race別のcallの平均値（＝通過率）", "race列の要素数", "全体のcallの平均値", "race別のcallの合計値"],
      answer: 0,
      explanation: "<code>group_by(race)</code> でrace別にグループ化し、各グループで <code>mean(call)</code> を計算。callがダミー変数(0/1)なので平均=割合。" },
    { id: "s02-m07", chapter: "第5章 データ集計", type: "mc",
      question: "<code>mean(wageBefore < 5.05)</code> は何を計算する？",
      choices: ["wageBeforeが5.05未満の割合", "wageBeforeの平均が5.05未満かどうか", "5.05未満のwageBeforeの平均", "wageBeforeから5.05を引いた平均"],
      answer: 0,
      explanation: "<code>wageBefore < 5.05</code> は各要素がTRUE/FALSEの論理ベクトルを返す。<code>mean()</code> でTRUEの割合を計算する。" },
    { id: "s02-m08", chapter: "第5章 データ集計", type: "mc",
      question: "<code>table()</code> のデフォルトの動作として正しいのは？",
      choices: ["NAを無視して集計する", "NAも集計に含める", "NAがあるとエラーになる", "NAを0として扱う"],
      answer: 0,
      explanation: "<code>table()</code> はデフォルトでNAを無視する。NAも含めるには <code>table(exclude = NULL)</code> を使う。" },

    { id: "s02-e01", chapter: "第5章 データ集計", type: "essay",
      question: "差の差分法（DID）の手順をRコードの一般形で説明せよ。",
      modelAnswer: "差の差分法は3ステップで行う。<br>①介入群・コントロール群ごとに、介入前後の測定値の平均を計算する：<code>データ |&gt; group_by(グループ列) |&gt; summarize(前 = mean(前列), 後 = mean(後列))</code><br>②各群の前後差を計算する：<code>mutate(diff = 後 - 前)</code><br>③介入群の差からコントロール群の差を引く：<code>diff[1] - diff[2]</code><br>これにより、時間の経過による共通の変化を取り除いた、介入の純粋な因果効果を推定できる。",
      points: ["group_by + summarize で群別に前後の平均を計算", "mutateで前後差を算出", "2群の差の差を計算して因果効果を推定"] },

    // ===== 第6章: ggplotによるグラフ作成 =====
    { id: "s03-t01", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotの基本構造（一般形）は？",
      back: "<code>データ |&gt; ggplot(aes(x = 列名, y = 列名)) + geom_xxx() + labs() + theme_minimal()</code>" },
    { id: "s03-t02", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで棒グラフを描く関数は？y軸の値をそのまま使うには？",
      back: "<code>geom_bar(stat = \"identity\")</code>" },
    { id: "s03-t03", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotでヒストグラムを描く関数は？ビンの幅と密度の指定方法は？",
      back: "<code>geom_histogram(binwidth = 幅, boundary = 境界値)</code>。密度は <code>aes(y = after_stat(density))</code>" },
    { id: "s03-t04", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで箱ひげ図を描く関数は？",
      back: "<code>geom_boxplot(fill = \"色\", outlier.shape = 形状, outlier.size = サイズ)</code>" },
    { id: "s03-t05", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで散布図を描く関数は？",
      back: "<code>geom_point(size = サイズ, alpha = 透明度)</code>" },
    { id: "s03-t06", chapter: "第6章 ggplotグラフ", type: "term",
      front: "ggplotで線グラフを描く関数は？",
      back: "<code>geom_line(linewidth = 太さ)</code>" },
    { id: "s03-t07", chapter: "第6章 ggplotグラフ", type: "term",
      front: "グラフのタイトルと軸ラベルを設定する関数の一般形は？",
      back: "<code>labs(x = \"x軸\", y = \"y軸\", title = \"タイトル\")</code>" },
    { id: "s03-t08", chapter: "第6章 ggplotグラフ", type: "term",
      front: "グラフを画像として保存する関数は？",
      back: "<code>ggsave(\"フォルダ/ファイル名.png\")</code>" },
    { id: "s03-t09", chapter: "第6章 ggplotグラフ", type: "term",
      front: "散布図でグループごとに色と形状を分ける方法は？",
      back: "<code>aes(color = グループ列, shape = グループ列)</code> で指定" },
    { id: "s03-t10", chapter: "第6章 ggplotグラフ", type: "term",
      front: "色を手動で指定する関数の一般形は？",
      back: "<code>scale_color_manual(name = \"凡例\", values = c(\"値\" = \"色コード\", ...))</code>" },

    { id: "s03-m01", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "ggplotの各レイヤーを繋ぐ記号は？",
      choices: ["+（プラス記号）", "|>（パイプ演算子）", "&（アンパサンド）", ">>（二重矢印）"],
      answer: 0,
      explanation: "ggplotのレイヤーは <code>+</code> で繋ぐ。パイプ <code>|&gt;</code> はデータをggplotに渡すときに使うが、ggplot内部のレイヤー結合には <code>+</code>。" },
    { id: "s03-m02", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "ヒストグラムでy軸を密度にするための指定は？",
      choices: ["aes(y = after_stat(density))", "aes(y = density)", "geom_histogram(density = TRUE)", "scale_y_density()"],
      answer: 0,
      explanation: "<code>after_stat(density)</code> で統計変換後の密度値をy軸に使用する。" },
    { id: "s03-m03", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "箱ひげ図が表現する5つの要約統計量は？",
      choices: ["最小値・Q1・中央値・Q3・最大値", "平均・標準偏差・最小・最大・中央値", "Q1・Q2・Q3・Q4・平均", "最小値・平均・中央値・最頻値・最大値"],
      answer: 0,
      explanation: "箱ひげ図は最小値、第1四分位数(Q1)、中央値(Q2)、第3四分位数(Q3)、最大値の5つを表現する。" },
    { id: "s03-m04", chapter: "第6章 ggplotグラフ", type: "mc",
      question: "散布図で点が重なって見づらいとき、有効な対策は？",
      choices: ["alpha（透明度）を下げる", "点のサイズを大きくする", "軸の範囲を狭める", "線グラフに変更する"],
      answer: 0,
      explanation: "透明度(alpha)を下げると、点が重なっている部分が濃くなり、密度を視覚的に表現できる。サイズを小さくすることも有効。" },

    // ===== 第7章: 統計分析 =====
    { id: "s03-t11", chapter: "第7章 統計分析", type: "term",
      front: "2変数の相関係数を計算する関数の一般形は？",
      back: "<code>cor(x, y)</code> または <code>データ |&gt; summarise(r = cor(列名1, 列名2))</code>" },
    { id: "s03-t12", chapter: "第7章 統計分析", type: "term",
      front: "Q-Qプロットを作成する関数の一般形は？",
      back: "<code>qqplot(ベクトル1, ベクトル2, xlab = \"x軸\", ylab = \"y軸\")</code>" },
    { id: "s03-t13", chapter: "第7章 統計分析", type: "term",
      front: "Q-Qプロットに45度線を追加するコードは？",
      back: "<code>abline(0, 1)</code>（切片0、傾き1の直線）" },
    { id: "s03-t14", chapter: "第7章 統計分析", type: "term",
      front: "$k$平均法を実行する関数の一般形は？",
      back: "<code>kmeans(データ, centers = k, nstart = 試行回数)</code>" },
    { id: "s03-t15", chapter: "第7章 統計分析", type: "term",
      front: "$k$平均法の結果からクラスター中心点を確認する方法は？",
      back: "<code>結果$centers</code>" },
    { id: "s03-t16", chapter: "第7章 統計分析", type: "term",
      front: "$k$平均法の結果から各データのクラスター番号を確認する方法は？",
      back: "<code>結果$cluster</code>" },
    { id: "s03-t17", chapter: "第7章 統計分析", type: "term",
      front: "自然対数変換の数学的性質として、対数の差は何に近似できる？",
      back: "$\\log(x_2) - \\log(x_1) = \\log\\left(\\frac{x_2}{x_1}\\right) \\approx \\frac{x_2 - x_1}{x_1}$（変化率に近似）" },

    { id: "s03-m05", chapter: "第7章 統計分析", type: "mc",
      question: "$k$平均法のクラスター番号について正しいのは？",
      choices: ["番号に意味はなく、実行のたびに変わりうる", "常にクラスター1が最大のクラスター", "番号が小さいほど中心に近い", "番号は政党に対応する"],
      answer: 0,
      explanation: "クラスター番号は任意であり、意味はない。実行のたびに初期値が異なるため番号が変わりうる。" },
    { id: "s03-m06", chapter: "第7章 統計分析", type: "mc",
      question: "Q-Qプロットで点が45度線の上にある場合、何を意味する？",
      choices: ["y軸側（縦軸）の変数の値が大きい", "x軸側（横軸）の変数の値が大きい", "2つの分布が同じ", "外れ値がある"],
      answer: 0,
      explanation: "45度線より上にある点は、y軸に対応する変数の分位数がx軸に対応する変数の分位数よりも大きいことを示す。" },
    { id: "s03-m07", chapter: "第7章 統計分析", type: "mc",
      question: "<code>log(0)</code> の結果は？",
      choices: ["-Inf", "0", "NA", "エラーになる"],
      answer: 0,
      explanation: "$\\log(0) = -\\infty$ なので、Rでは <code>-Inf</code> を返す。負の値の場合は <code>NaN</code> を返す。" },
    { id: "s03-m08", chapter: "第7章 統計分析", type: "mc",
      question: "対数変換が有効なのはどのような場合？",
      choices: ["データの分布が右に大きく偏っているとき", "データが正規分布に従うとき", "データに負の値が多いとき", "データの平均が0に近いとき"],
      answer: 0,
      explanation: "収入や人口のように右に偏った分布に対数変換を行うと、偏りが修正されより対称的な分布になる。ただし0や負の値には適用不可。" },

    { id: "s03-e01", chapter: "第7章 統計分析", type: "essay",
      question: "$k$平均法のアルゴリズムの手順を4つのステップで説明せよ。",
      modelAnswer: "①$k$個のクラスターの初期中心点を（ランダムに）選択する。<br>②各データ点を、最も近い中心点を持つクラスターに割り当てる（ユークリッド距離で判定）。<br>③各クラスターの新しい中心点を、そのクラスターに属する全データ点の平均座標として計算する。<br>④クラスターへの割り当てが変化しなくなるまで②と③を繰り返す。<br>Rでは <code>kmeans(データ, centers = k, nstart = 試行回数)</code> で実行する。<code>nstart</code>で複数の初期値を試し、最良の結果を選ぶ。",
      points: ["初期中心点のランダム選択", "各点を最近接クラスターに割り当て→中心点再計算の繰り返し", "収束条件（割り当てが変化しなくなるまで）"] },
    { id: "s03-e02", chapter: "第6章 ggplotグラフ", type: "essay",
      question: "ggplotで散布図を作成し、グループごとに色と形状を分けて、軸ラベルとタイトルを設定する完全なコードの一般形を書け。",
      modelAnswer: "<code>データ |&gt;<br>&nbsp;&nbsp;ggplot(aes(x = 列名1, y = 列名2, color = グループ列, shape = グループ列)) +<br>&nbsp;&nbsp;geom_point(size = サイズ, alpha = 透明度) +<br>&nbsp;&nbsp;scale_color_manual(name = \"凡例\", values = c(\"値1\" = \"色1\", \"値2\" = \"色2\")) +<br>&nbsp;&nbsp;scale_shape_manual(name = \"凡例\", values = c(\"値1\" = 16, \"値2\" = 17)) +<br>&nbsp;&nbsp;labs(x = \"x軸ラベル\", y = \"y軸ラベル\", title = \"タイトル\") +<br>&nbsp;&nbsp;theme_minimal(base_family = \"フォント名\")</code>",
      points: ["aes()でcolor, shapeにグループ変数を指定", "scale_color_manual / scale_shape_manual で色と形を手動設定", "labs()でラベルとタイトルを設定し、theme_minimal()でテーマ適用"] },

    // ===== 第8章: ループと条件文 =====
    { id: "s04-t01", chapter: "第8章 ループと条件文", type: "term",
      front: "Rで同じ処理を繰り返すfor構文の一般形は？",
      back: "<code>for (i in ベクトル) { 繰り返したい処理 }</code><br><code>i</code> にベクトルの値が1つずつ順番に入る" },
    { id: "s04-t02", chapter: "第8章 ループと条件文", type: "term",
      front: "forループの結果を保存するために、先に「入れ物」を作るコードは？",
      back: "<code>results &lt;- rep(NA, length(values))</code><br>各回で <code>results[i] &lt;- 計算式</code> と保存する" },
    { id: "s04-t03", chapter: "第8章 ループと条件文", type: "term",
      front: "条件によって処理を変えるif/else構文の一般形は？",
      back: "<code>if (条件) { TRUEのときの処理 } else { FALSEのときの処理 }</code>" },
    { id: "s04-t04", chapter: "第8章 ループと条件文", type: "term",
      front: "条件が3つ以上あるときに使う構文は？",
      back: "<code>else if</code>。<code>if (条件1) {...} else if (条件2) {...} else {...}</code> の形で書く" },
    { id: "s04-t05", chapter: "第8章 ループと条件文", type: "term",
      front: "演算子 <code>%%</code> は何を計算する？",
      back: "割り算の余り（剰余）。例: <code>5 %% 2</code> → 1" },
    { id: "s04-t06", chapter: "第8章 ループと条件文", type: "term",
      front: "xが偶数かどうかを判定する条件式は？",
      back: "<code>x %% 2 == 0</code>（2で割った余りが0なら偶数）" },
    { id: "s04-t07", chapter: "第8章 ループと条件文", type: "term",
      front: "else ifが複数あるとき、条件はどの順で調べられ、どの処理が実行される？",
      back: "上から順に調べられ、<b>最初に当てはまった処理だけ</b>が実行される" },

    { id: "s04-m01", chapter: "第8章 ループと条件文", type: "mc",
      question: "<code>for (i in 1:3) { print(i) }</code> の出力は？",
      choices: ["1、2、3が順に表示される", "3だけが表示される", "1 2 3が1行で表示される", "エラーになる"],
      answer: 0,
      explanation: "<code>i</code> に1、2、3が順番に入り、そのたびに <code>print(i)</code> が実行される。" },
    { id: "s04-m02", chapter: "第8章 ループと条件文", type: "mc",
      question: "score &lt;- 55 のとき、<code>if (score >= 80) print(\"A\") else if (score >= 60) print(\"B\") else print(\"C\")</code> の出力は？",
      choices: ["C", "B", "A", "何も表示されない"],
      answer: 0,
      explanation: "55は80以上でも60以上でもないので、最後の <code>else</code> の処理が実行され \"C\" が表示される。" },
    { id: "s04-m03", chapter: "第8章 ループと条件文", type: "mc",
      question: "ifの中の条件が満たすべき要件は？",
      choices: ["TRUEまたはFALSEのどちらか1つになること", "数値を返すこと", "ベクトル全体を返すこと", "文字列を返すこと"],
      answer: 0,
      explanation: "ifの条件はTRUE/FALSEのどちらか1つになる必要がある。" },
    { id: "s04-m04", chapter: "第8章 ループと条件文", type: "mc",
      question: "for構文が特に役立つのはどんなとき？",
      choices: ["処理が複雑なときや、各回の計算を順番に確認したいとき", "単純な掛け算をするとき", "ベクトル演算より常に速いから", "データを読み込むとき"],
      answer: 0,
      explanation: "単純な計算なら <code>values * 2</code> のようにベクトル演算の方が簡単。forは処理が複雑なときに役立つ。" },

    // ===== 第9章: 予測と予測誤差 =====
    { id: "s04-t08", chapter: "第9章 予測と予測誤差", type: "term",
      front: "予測誤差の定義は？",
      back: "予測誤差 ＝ 実際の結果 − 予測された結果" },
    { id: "s04-t09", chapter: "第9章 予測と予測誤差", type: "term",
      front: "予測誤差の平均値のことを何と呼ぶ？",
      back: "バイアス" },
    { id: "s04-t10", chapter: "第9章 予測と予測誤差", type: "term",
      front: "RMSE（2乗平均平方根誤差）の計算方法と意味は？",
      back: "予測誤差を2乗して平均し、平方根を取ったもの。$\\sqrt{\\frac{1}{n}\\sum \\text{誤差}^2}$。予測誤差の<b>平均的な大きさ</b>を表す" },
    { id: "s04-t11", chapter: "第9章 予測と予測誤差", type: "term",
      front: "選挙の勝敗のように、結果がどのカテゴリに属するかを予測する問題を何と呼ぶ？",
      back: "分類問題（予測は正しいか誤りかのどちらかとして評価される）" },
    { id: "s04-t12", chapter: "第9章 予測と予測誤差", type: "term",
      front: "「偽陽性」とはどのような予測の誤り？",
      back: "実際には<b>陰性</b>であるのに<b>陽性</b>と予測する場合" },
    { id: "s04-t13", chapter: "第9章 予測と予測誤差", type: "term",
      front: "「偽陰性」とはどのような予測の誤り？",
      back: "実際には<b>陽性</b>であるのに<b>陰性</b>と予測する場合" },
    { id: "s04-t14", chapter: "第9章 予測と予測誤差", type: "term",
      front: "文字列を日付型に変換する関数と、変換のメリットは？",
      back: "<code>as.Date(\"YYYY-MM-DD\")</code>。日付どうしの引き算で日数を計算できるようになる" },
    { id: "s04-t15", chapter: "第9章 予測と予測誤差", type: "term",
      front: "<code>sign(x)</code> は何を返す？",
      back: "xの符号。正なら1、負なら-1を返す。予測と実際の勝敗の一致確認に使える" },

    { id: "s04-m05", chapter: "第9章 予測と予測誤差", type: "mc",
      question: "2008年大統領選の世論調査予測で、バイアスが1.06とほぼ0に近かった。この結果の解釈は？",
      choices: ["世論調査からの予測に大きな偏りはない", "予測は完全に正確である", "世論調査は役に立たない", "RMSEも必ず0に近くなる"],
      answer: 0,
      explanation: "バイアス（平均予測誤差）が0に近い＝系統的な偏りがない。ただし個々の誤差の大きさはRMSE（5.91）で別に評価する。" },
    { id: "s04-m06", chapter: "第9章 予測と予測誤差", type: "mc",
      question: "予測（横軸）と実際の結果（縦軸）の散布図で、点が45度線の上にあることの意味は？",
      choices: ["予測と実際が一致している", "予測が過大である", "予測が過小である", "勝敗の予測が外れている"],
      answer: 0,
      explanation: "45度線上では横軸の値＝縦軸の値、つまり予測値と実際の値が一致している。" },
    { id: "s04-m07", chapter: "第9章 予測と予測誤差", type: "mc",
      question: "予測マージンと実際のマージンの散布図（縦軸0と横軸0の線で4分割）で、勝敗の予測が当たっているのはどの領域？",
      choices: ["右上と左下", "右下と左上", "右上と右下", "左上と左下"],
      answer: 0,
      explanation: "右上（予測も実際も正）と左下（予測も実際も負）は符号が一致＝勝敗予測が的中。右下と左上は外れ。" },
    { id: "s04-m08", chapter: "第9章 予測と予測誤差", type: "mc",
      question: "<code>sum(EV[actual_margin > 0])</code> は何を計算している？",
      choices: ["マージンが正の州の選挙人票の合計", "全州の選挙人票の合計", "マージンが正の州の数", "選挙人票の平均"],
      answer: 0,
      explanation: "<code>EV[条件]</code> で条件を満たす行のEVだけを取り出し、<code>sum()</code> で合計する。オバマが勝った州の選挙人票の合計。" },
    { id: "s04-m09", chapter: "第9章 予測と予測誤差", type: "mc",
      question: "2008年の分析で、世論調査から勝敗の予測が外れた州（IN, MO, NC）に共通する特徴は？",
      choices: ["いずれも接戦だった", "いずれも大差だった", "いずれも調査数が多かった", "いずれも南部の州だった"],
      answer: 0,
      explanation: "予測が外れた3州はいずれもマージンが±5%ポイント以内の接戦州だった。" },

    { id: "s04-e01", chapter: "第9章 予測と予測誤差", type: "essay",
      question: "世論調査データから州ごとの選挙予測を作り、その予測精度をバイアスとRMSEで評価する手順を説明せよ。",
      modelAnswer: "①各調査についてマージン（オバマの支持率 − マケインの支持率）と、選挙日までの日数（<code>as.Date()</code>で日付型に変換して引き算）を計算する。<br>②<code>group_by(state)</code> で州ごとにグループ化し、<code>filter(days_to_election == min(days_to_election))</code> で選挙に最も近い調査だけを残し、そのマージンの平均を予測値とする。<br>③実際の選挙結果と <code>inner_join()</code> で結合し、予測誤差＝実際のマージン − 予測マージンを計算する。<br>④バイアス＝<code>mean(error)</code>（予測誤差の平均）、RMSE＝<code>sqrt(mean(error^2))</code> で予測の偏りと平均的な誤差の大きさを評価する。",
      points: ["直近の調査に絞る処理（group_by → filter で days_to_election が最小）", "予測誤差＝実際 − 予測 の定義と結合（inner_join）", "バイアス＝mean(error)、RMSE＝sqrt(mean(error^2)) の計算式"] },

    // ===== 第10章: 線形回帰 =====
    { id: "s04-t16", chapter: "第10章 線形回帰", type: "term",
      front: "線形回帰モデルの式は？（記号の意味も）",
      back: "$Y = \\alpha + \\beta X + \\epsilon$<br>$Y$＝結果変数、$X$＝予測変数、$\\alpha$＝切片、$\\beta$＝傾き、$\\epsilon$＝誤差項" },
    { id: "s04-t17", chapter: "第10章 線形回帰", type: "term",
      front: "回帰係数（傾き）$\\beta$ の解釈は？",
      back: "$X$が1単位増加するときに、$Y$が平均してどれだけ増加するかを表す" },
    { id: "s04-t18", chapter: "第10章 線形回帰", type: "term",
      front: "授業で線形回帰の推定に使う関数とパッケージは？",
      back: "fixestパッケージの <code>feols()</code>（教科書のlm()より高速・高機能）" },
    { id: "s04-t19", chapter: "第10章 線形回帰", type: "term",
      front: "feols()で回帰を推定する一般形は？",
      back: "<code>fit &lt;- feols(結果変数 ~ 予測変数, data = データ)</code><br>切片は自動的にモデルに加えられる" },
    { id: "s04-t20", chapter: "第10章 線形回帰", type: "term",
      front: "推定結果から係数（切片と傾き）を取り出す関数は？",
      back: "<code>coef(fit)</code>" },
    { id: "s04-t21", chapter: "第10章 線形回帰", type: "term",
      front: "推定結果から予測値（当てはめ値）を取り出す関数は？",
      back: "<code>fitted(fit)</code>" },
    { id: "s04-t22", chapter: "第10章 線形回帰", type: "term",
      front: "推定結果から残差を取り出す関数は？残差の定義は？",
      back: "<code>resid(fit)</code>。残差 ＝ 実際の値 − 予測値" },
    { id: "s04-t23", chapter: "第10章 線形回帰", type: "term",
      front: "決定係数 $R^2$ の定義式は？",
      back: "$R^2 = \\frac{\\text{TSS} - \\text{RSS}}{\\text{TSS}} = 1 - \\frac{\\text{RSS}}{\\text{TSS}}$<br>TSS＝全変動平方和、RSS＝残差平方和" },
    { id: "s04-t24", chapter: "第10章 線形回帰", type: "term",
      front: "決定係数 $R^2$ の取りうる範囲と意味は？",
      back: "0から1の範囲。1に近いほどモデルが結果変数の変動をよく説明していることを示す" },
    { id: "s04-t25", chapter: "第10章 線形回帰", type: "term",
      front: "fixestで推定結果から決定係数を直接取り出す関数は？",
      back: "<code>r2(fit, type = \"r2\")</code>" },
    { id: "s04-t26", chapter: "第10章 線形回帰", type: "term",
      front: "ggplotで散布図に回帰直線を重ねる（信頼区間の帯なし）一般形は？",
      back: "<code>geom_smooth(method = \"lm\", se = FALSE)</code>" },
    { id: "s04-t27", chapter: "第10章 線形回帰", type: "term",
      front: "2つのデータフレームを結合するとき、共通の列名を区別する引数は？",
      back: "<code>suffix = c(\"_2008\", \"_2012\")</code> のように接尾辞を指定する<br>例: <code>inner_join(pres12, by = \"state\", suffix = c(\"_2008\", \"_2012\"))</code>" },

    { id: "s04-m10", chapter: "第10章 線形回帰", type: "mc",
      question: "顔の見た目スコアの回帰で傾きが約0.66だった。正しい解釈は？",
      choices: ["能力スコアが0.1増加するごとにマージンが約6.6%ポイント増加する", "能力スコアが1増えるとマージンが0.066増える", "相関係数が0.66である", "決定係数が0.66である"],
      answer: 0,
      explanation: "傾き0.66は「スコア1単位増→マージン0.66（66%ポイント）増」。スコア0.1増なら約6.6%ポイント増と解釈できる。" },
    { id: "s04-m11", chapter: "第10章 線形回帰", type: "mc",
      question: "フロリダ州の回帰分析で、パームビーチ郡を除外すると決定係数はどうなった？",
      choices: ["0.513から0.851に大きく改善した", "0.851から0.513に低下した", "ほとんど変わらなかった", "1になった"],
      answer: 0,
      explanation: "パームビーチ郡は残差が最大の外れ値。除外すると $R^2$ が0.513→0.851に大きく改善した。" },
    { id: "s04-m12", chapter: "第10章 線形回帰", type: "mc",
      question: "feols()のフォーミュラの正しい書き方は？",
      choices: ["結果変数 ~ 予測変数", "予測変数 ~ 結果変数", "結果変数 + 予測変数", "結果変数 == 予測変数"],
      answer: 0,
      explanation: "チルダ（~）の左が結果変数、右が予測変数。<code>feols(diff.share ~ d.comp, data = face)</code> のように書く。" },
    { id: "s04-m13", chapter: "第10章 線形回帰", type: "mc",
      question: "見た目スコアの回帰では残差のRMSEが約0.26だった。この解釈は？",
      choices: ["平均で約26%ポイントの誤差があり、予測はそれほど正確ではない", "誤差は0.26%で非常に正確", "決定係数が0.26である", "26%の州で予測が外れた"],
      answer: 0,
      explanation: "残差のRMSEは予測誤差の平均的な大きさ。マージンの単位で約0.26（26%ポイント）の誤差が生じている。" },
    { id: "s04-m14", chapter: "第10章 線形回帰", type: "mc",
      question: "残差プロット（横軸=予測値、縦軸=残差）の主な用途は？",
      choices: ["モデルの当てはまりを確認し、外れ値を見つける", "相関係数を計算する", "回帰直線の傾きを求める", "データの結合を確認する"],
      answer: 0,
      explanation: "残差プロットで残差が特に大きい点（例: パームビーチ郡）が外れ値としてわかる。" },

    { id: "s04-e02", chapter: "第10章 線形回帰", type: "essay",
      question: "決定係数（$R^2$）とは何か。定義式を示し、TSSとRSSからRで計算する方法を説明せよ。",
      modelAnswer: "決定係数はモデルによって説明された結果変数の変動の割合を表す指標である。<br>定義式は $R^2 = \\frac{\\text{TSS}-\\text{RSS}}{\\text{TSS}} = 1 - \\frac{\\text{RSS}}{\\text{TSS}}$。ここでTSSは全変動平方和 <code>sum((Y - mean(Y))^2)</code>、RSSは残差平方和 <code>sum(resid^2)</code> である。<br>Rでは <code>mutate(resid = resid(fit))</code> で残差を列として追加し、<code>summarise()</code> の中でTSS・RSSを計算して <code>(TSS - RSS) / TSS</code> を求める。<br>$R^2$ は0から1の値をとり、1に近いほどモデルが結果変数の変動をよく説明している。なお、fixestでは <code>r2(fit, type = \"r2\")</code> で直接取得できる。",
      points: ["定義式 R² = (TSS−RSS)/TSS と、TSS・RSSの意味", "Rでの計算手順（resid()で残差→TSS・RSS→R²）", "0〜1の範囲で、1に近いほど説明力が高いという解釈"] },
    { id: "s04-e03", chapter: "第10章 線形回帰", type: "essay",
      question: "フロリダ州の郡別データの回帰分析を例に、外れ値が回帰結果に与える影響と、その確認・対処の流れを説明せよ。",
      modelAnswer: "2000年のブキャナンの得票数を1996年のペローの得票数で回帰すると、$R^2$は約0.51だった。<br>残差プロット（横軸=予測値、縦軸=残差）を描くと、残差が突出して大きい郡があり、<code>filter(resid == max(resid))</code> で確認するとパームビーチ郡だとわかる。この郡では予想以上にブキャナンの得票が多かった。<br>パームビーチ郡を <code>filter(county != \"PalmBeach\")</code> で除外して同じ回帰を行うと、$R^2$は約0.85に大きく改善する。<br>散布図に2本の回帰直線（除外前・除外後）を重ねると、パームビーチ郡が回帰直線から大きく外れていることが視覚的に確認できる。このように外れ値は回帰の当てはまりを大きく悪化させる。",
      points: ["残差プロットや resid == max(resid) による外れ値（パームビーチ郡）の特定", "外れ値除外の前後で R² が 0.513→0.851 に改善すること", "外れ値が回帰直線・当てはまりに大きな影響を与えるという結論"] },

    // ===== 第11章: 回帰と因果推論 =====
    { id: "s04-t28", chapter: "第11章 回帰と因果推論", type: "term",
      front: "2値トリートメントの実験データで、回帰の傾き係数は何と解釈できる？",
      back: "平均トリートメント効果の推定値。トリートメントグループとコントロールグループの<b>平均の差</b>と等しい" },
    { id: "s04-t29", chapter: "第11章 回帰と因果推論", type: "term",
      front: "回帰係数を因果効果と解釈するために重要な仮定は？",
      back: "トリートメントの割り当てが<b>ランダム</b>であるなどの仮定" },
    { id: "s04-t30", chapter: "第11章 回帰と因果推論", type: "term",
      front: "重回帰モデルの式は？",
      back: "$Y = \\alpha + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p + \\epsilon$" },
    { id: "s04-t31", chapter: "第11章 回帰と因果推論", type: "term",
      front: "重回帰モデルの各係数 $\\beta_j$ の解釈は？",
      back: "<b>他の予測変数を一定に保ったときに</b>、$X_j$ が1単位増加することと$Y$の平均的な変化の関係を表す" },
    { id: "s04-t32", chapter: "第11章 回帰と因果推論", type: "term",
      front: "因子変数（文字列の変数）を回帰に入れるとRはどう処理する？",
      back: "自動的に指標変数（ダミー変数）に変換して回帰に用いる。基準カテゴリ以外の各カテゴリに係数が付く" },
    { id: "s04-t33", chapter: "第11章 回帰と因果推論", type: "term",
      front: "フォーミュラで <code>X1 * X2</code> と書くと何がモデルに含まれる？",
      back: "$X_1$、$X_2$それぞれの<b>主効果</b>と<b>交互作用項</b>（$X_1 \\times X_2$）がまとめて含まれる" },
    { id: "s04-t34", chapter: "第11章 回帰と因果推論", type: "term",
      front: "交互作用項の係数は何を表す？",
      back: "グループによってトリートメント効果がどれだけ異なるか（不均一トリートメント効果）" },
    { id: "s04-t35", chapter: "第11章 回帰と因果推論", type: "term",
      front: "推定済みモデルから任意の予測変数の値に対する予測値を計算する関数は？",
      back: "<code>predict(fit, newdata = データフレーム)</code>" },

    { id: "s04-m15", chapter: "第11章 回帰と因果推論", type: "mc",
      question: "インドの女性割当実験で <code>feols(water ~ reserved, data = women)</code> のreservedの係数9.25の解釈は？",
      choices: ["女性割当により飲用水設備が平均9.25件増える（平均因果効果）", "女性議長の割合が9.25%増える", "飲用水設備の総数が9.25である", "灌漑設備が9.25件増える"],
      answer: 0,
      explanation: "割当はランダムなので、reservedの係数は平均因果効果の推定値であり、2グループの平均の差と一致する。" },
    { id: "s04-m16", chapter: "第11章 回帰と因果推論", type: "mc",
      question: "女性割当実験の結果（飲用水は増加、灌漑は効果なし）はどんな仮説と整合的？",
      choices: ["女性政治家は女性有権者の求める政策をより支持しやすい", "女性政治家は全ての公共事業を増やす", "割当は政策に影響しない", "灌漑設備の方が重要である"],
      answer: 0,
      explanation: "飲用水は女性有権者が求める政策であり、割当で増加。灌漑には有意な効果がなかった。" },
    { id: "s04-m17", chapter: "第11章 回帰と因果推論", type: "mc",
      question: "messagesを予測変数にした回帰で、<code>predict(fit_social, newdata = unique_messages)</code> の予測値と一致するものは？",
      choices: ["各メッセージのグループごとの実際の平均投票率", "全体の平均投票率", "各グループの中央値", "残差の平均"],
      answer: 0,
      explanation: "因子変数だけの回帰では、予測値は各グループの実際の平均と一致する。" },
    { id: "s04-m18", chapter: "第11章 回帰と因果推論", type: "mc",
      question: "社会的プレッシャー実験で、交互作用項 <code>primary2004:messagesNeighbors</code> の係数（0.027）が表すのは？",
      choices: ["2004年に投票したかどうかでNeighborsメッセージの効果がどれだけ異なるか", "2004年の投票が2006年の投票に与える効果", "Neighborsメッセージ自体の効果", "全体の投票率の上昇分"],
      answer: 0,
      explanation: "交互作用項の係数は、グループ（2004年投票の有無）によるトリートメント効果の違い＝不均一トリートメント効果を表す。" },

    { id: "s04-e04", chapter: "第11章 回帰と因果推論", type: "essay",
      question: "トリートメント効果が個人の特徴によって異なるかどうかを、交互作用項を含む回帰で調べる方法を、社会的プレッシャー実験を例に説明せよ。",
      modelAnswer: "トリートメント効果がグループや個人の特徴によって異なる可能性（不均一トリートメント効果）を調べるには、回帰モデルに交互作用項を含める。<br>社会的プレッシャー実験では、NeighborsグループとControlグループに絞ったうえで、<code>feols(primary2006 ~ primary2004 * messages, data = social_neighbor)</code> と書く。<code>*</code> により、primary2004とmessagesの主効果と交互作用項がまとめてモデルに含まれる。<br>回帰式は $Y = \\alpha + \\beta_1 \\text{Primary2004} + \\beta_2 \\text{Neighbors} + \\beta_3(\\text{Primary2004} \\times \\text{Neighbors}) + \\epsilon$ となる。<br>交互作用項の係数 $\\beta_3$（推定値0.027）は、2004年に投票したかどうかによってNeighborsメッセージの効果がどれだけ異なるかを表す。係数が正で有意なので、過去に投票した人ほどメッセージの効果が大きい、すなわち不均一トリートメント効果が存在するとわかる。",
      points: ["X1 * X2 と書くと主効果＋交互作用項がモデルに入ること", "交互作用項の係数＝グループによるトリートメント効果の違い（不均一トリートメント効果）", "実験例での解釈（2004年投票者ほどNeighborsの効果が大きい）"] }
  ]
};
